[package]
name = "iris"
version = "0.4.0"
authors = ["Matthieu Buffet <matthieu@buffet.re>"]
edition = "2018"

[dependencies]
libc = "0.2"
seccomp-sys = { path = "../seccomp-sys" }
serde = { version = "1.0.124", features = ["derive"] }
bincode = "1.3.2"

